version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: workflow_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=workflow_automation
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: workflow_backend
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB_NAME=workflow_automation
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-for-jwt}
      - DEBUG=true
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  telegram-bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    container_name: workflow_bot
    environment:
      - API_HOST=backend
      - API_PORT=8000
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./telegram_bot:/app/telegram_bot

volumes:
  mongodb_data:
